/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni */

#ifndef _Included_com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni
#define _Included_com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni
 * Method:    jniIsTileDBArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni_jniIsTileDBArray
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni
 * Method:    jniListTileDBArrays
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_intel_genomicsdb_reader_GenomicsDBFeatureReaderJni_jniListTileDBArrays
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
